# we are extending everything from tomcat:8.0 image ...
FROM tomcat:9
MAINTAINER jlo_and_mredman
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY HW1.war /usr/local/tomcat/webapps/