pipeline {
    environment {
        registry = "longofest/hw1-image"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    agent any
    
    stages {
        stage('Clone') {
            steps{
                git 'https://github.com/mshalap/swe645-group-project-jlo'
                withAnt(installation: 'Ant1.10.8') {
                        bat'''
                        cd HW1
                        ant war
                        '''
                }
            }
        }

        stage('Build') {
            steps {
                script {
                  dockerImage = docker.build(registry + ":$BUILD_NUMBER", "./HW1")
                }

            }
        }

        stage('Push Image') {
            steps{
                script{
                    docker.withRegistry('',registryCredential){
                        dockerImage.push()
                    }
                }
            }
        }

		/*
        stage('Remove Unused Image') {
          steps{
            bat "docker rmi $registry:$BUILD_NUMBER"
          }
        }
		*/
		
		stage('Deploy Image') {
            steps{
               
               bat"""
                docker pull longofest/hw1-image:$BUILD_NUMBER
                kubectl --kubeconfig c:/Users/margaret64275/.kube/config set image deployment hw1 hw1-image=docker.io/longofest/hw1-image:$BUILD_NUMBER
                """
            }
        }


		
    }

     
}