pipeline {
    environment {
        registryAngular = "longofest/hw3-image-angular"
		registryRest = "longofest/hw3-image-rest"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    agent any
    
    stages {
        stage('Clone') {
            steps{
                git 'https://github.com/mshalap/swe645-group-project-jlo'
            }
        }

        stage('Build Angular') {
            steps {
                script {
                  dockerImageAngular = docker.build(registryAngular + ":$BUILD_NUMBER", "./HW3/student-survey")
                }
            }
        }
		
		stage('Build REST') {
            steps {
				script {
                  dockerImageRest = docker.build(registryRest + ":$BUILD_NUMBER", "./HW3/rest")
                }
            }
        }

        stage('Push Angular Image') {
            steps{
                script{
                    docker.withRegistry('',registryCredential){
                        dockerImageAngular.push()
                    }
                }
            }
        }
		
		stage('Push REST Image') {
            steps{
                script{
                    docker.withRegistry('',registryCredential){
                        dockerImageRest.push()
                    }
                }
            }
        }
		
		stage('Deploy Angular Image') {
            steps{
               
               bat"""
                docker pull longofest/hw3-image-angular:$BUILD_NUMBER
                kubectl --kubeconfig c:/Users/margaret64275/.kube/config set image deployment hw1 hw1-image=docker.io/longofest/hw1-image:$BUILD_NUMBER
                """
            }
        }
		
		stage('Deploy REST Image') {
            steps{
               
               bat"""
                docker pull longofest/hw3-image-rest:$BUILD_NUMBER
                kubectl --kubeconfig c:/Users/margaret64275/.kube/config set image deployment hw1 hw1-image=docker.io/longofest/hw1-image:$BUILD_NUMBER
                """
            }
        }
		
    }

     
}