# we are extending everything from tomcat:9.0 image ...
FROM tomcat:9.0
LABEL maintainer=jlo_and_mredman
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat

COPY target/HW3-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/