pipeline {
    environment {
        registry = "longofest/hw3-image"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    agent any
    tools{
        maven 'Maven 3.3.9' 
    }
    
    stages {
        stage('Clone') {
            steps{
                git 'https://github.com/mshalap/swe645-group-project-jlo'
               	bat"""
               	cd HW3/rest
               	mvn package
               	""" 
            }
        }

        stage('Build') {
            steps {
                script {
                  dockerImage = docker.build(registry + ":$BUILD_NUMBER", "./HW3")
                }

            }
        }

        stage('Push Image') {
            steps{
                script{
                    docker.withRegistry('',registryCredential){
                        dockerImage.push()
                    }
                }
            }
        }
		
		stage('Deploy Image') {
            steps{
               
               bat"""
                docker pull longofest/hw3-image:$BUILD_NUMBER
                kubectl --kubeconfig c:/Users/margaret64275/.kube/config set image deployment hw3-rest hw3-image=docker.io/longofest/hw3-image:$BUILD_NUMBER
                """
            }
        }
		
    }

     
}